name: nutrition-planner-application-backend

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: nutrition_planner
    volumes:
      - nutrition_planner_db_disk:/var/lib/postgresql/data
    networks:
      - nutrition-network

  my-keycloak:
    image: quay.io/keycloak/keycloak:26.5.5
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_LOG_LEVEL: info
    command: ["start-dev"]
    ports:
      - "8081:8080"
    networks:
      - nutrition-network

networks:
  nutrition-network:
    driver: bridge

volumes:
  nutrition_planner_db_disk:
    driver: local
