CREATE TABLE food_product
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name          VARCHAR(255)     NOT NULL,
    calories      DOUBLE PRECISION NOT NULL,
    protein       DOUBLE PRECISION NOT NULL,
    fat           DOUBLE PRECISION NOT NULL,
    carbohydrates DOUBLE PRECISION NOT NULL,
    price         DOUBLE PRECISION NOT NULL
);